### ISSUE TITLE
Ability to drain idle clients without ending the pool

### ISSUE THREAD

**Issue by cornerman** [postgres-pool/postgres-pool#67]
I have a use-case, where I would like to work with a connection pool, but actively drain all idle clients at certain time intervals.

This is basically already implemented in the `pool.end()` method, but this does not only drain idle clients, but actually destroys the pool, which then cannot be used anymore. I would like to keep on using the pool instance, but make sure that all idle clients have been cleaned up.

Currently, I am creating a new pool for each situation and then call `end` on it. Though, I would prefer to just keep one pool instance.

This would be fixed by making this method public: https://github.com/postgres-pool/postgres-pool/blob/main/src/index.ts#L455

Would that be an option?

**Comment by jgeurts** [comment]
This should be fixed with v8.0.0
