### ISSUE TITLE
Is it possible to handle: "Connection terminated unexpectedly" errors?

### ISSUE THREAD

**Issue by moltar** [postgres-pool/postgres-pool#68]
Would it be within the scope of this package to handle the following error?

> Connection terminated unexpectedly

https://github.com/brianc/node-postgres/blob/970804b6c110fab500da9db71d68d04e0ecea406/packages/pg/lib/client.js#L132

**Comment by jgeurts** [comment]
Open to ideas/suggestions :)

**Comment by jgeurts** [comment]
Closing for now. Please re-open and/or submit a PR!
